### ISSUE TITLE
VSync not working/tearing on NVidia (970m).

### ISSUE THREAD

**Issue by natevm** [a-day-old-bagel/DualityEngine#18]
Both horizontal and diagonal screen tearing on Nvidia 970 m occur. I'd like to know if any other nvidia cards do this. Running the game engine on my Intel integrated graphics, I have no tearing issues.  

![image](https://cloud.githubusercontent.com/assets/13104331/12376280/7408d642-bca8-11e5-880a-9b2a1007404c.png)

**Comment by natevm** [comment]
When turning off Aero, I stop noticing the diagonal tear with my Nvidia card...

**Comment by natevm** [comment]
Discovered my system wasn't running at native resolution. By simply switching to native resolution, the diagonal tearing vanishes. I believe this is a bug doesn't have anything to do with the engine, so I'm closing this issue.

**Comment by a-day-old-bagel** [comment]
Oh that's good then.  How did you make it run at native res?
Or do you mean that windows itself wasn't at native res either?

**Comment by natevm** [comment]
I simply changed my resolution preferences in windows. I didn't make any changes to Duality. I believe it's a windows desktop composition bug when working with nvidia cards. Could be specific to the 970 m's.
