### ISSUE TITLE
Assimp loads obj files neglecting last face

### ISSUE THREAD

**Issue by a-day-old-bagel** [a-day-old-bagel/DualityEngine#19]
This may be a bug on their end and I've submitted an issue to the assimp github page.
If your obj file doesn't have a trailing newline character after the last line (which is usually a face-specifying line), that line won't be loaded.  They probably have a regex that includes the newline character so it misses those cases.

Anyway, to fix it for now, just make sure there's an empty line at the end of your obj file.

**Comment by natevm** [comment]
Awesome! Glad that's taken care of. I wouldn't have thought to make sure obj's have a carriage return at the end. Nice work.
